kind: pipeline
name: static-tests

steps:
- name: flake8
  image: alpine/flake8:3.7.9
  commands:
  - flake8

# fails on local development
#- name: leaks
#  image: zricethezav/gitleaks:v6.2.0
#

---
kind: pipeline
name: integration-tests

concurrency:
  limit: 1

depends_on:
- static-tests

steps:
- name: copy code to target
  image: appleboy/drone-scp:1.6.2
  settings:
    host:
      from_secret: target_hostname
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port:
      from_secret: target_port
    source: .
    target: /app-test/code
    rm: true


- name: 1 - process hoover testdata, run UI tests
  image: appleboy/drone-ssh:1.6.3
  environment:
    TEST_ADMIN_PASSWORD:
      from_secret: test_admin_password
  settings:
    host:
      from_secret: target_hostname
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port:
      from_secret: target_port
    envs: [test_admin_password]
    command_timeout: 120m
    script:
      - set -x
      - set -e
      - cd /app-test/code
      - export TEST_ADMIN_PASSWORD=$${TEST_ADMIN_PASSWORD}
      - ./ci/run-integration-tests.sh 1


- name: 2 - test backup, restore
  image: appleboy/drone-ssh:1.6.3
  environment:
    TEST_ADMIN_PASSWORD:
      from_secret: test_admin_password
  settings:
    host:
      from_secret: target_hostname
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port:
      from_secret: target_port
    envs: [test_admin_password]
    command_timeout: 120m
    script:
      - set -x
      - set -e
      - cd /app-test/code
      - export TEST_ADMIN_PASSWORD=$${TEST_ADMIN_PASSWORD}
      - ./ci/run-integration-tests.sh 2


- name: 3 - integration tests
  image: appleboy/drone-ssh:1.6.3
  environment:
    TEST_ADMIN_PASSWORD:
      from_secret: test_admin_password
  settings:
    host:
      from_secret: target_hostname
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port:
      from_secret: target_port
    envs: [test_admin_password]
    command_timeout: 120m
    script:
      - set -x
      - set -e
      - cd /app-test/code
      - export TEST_ADMIN_PASSWORD=$${TEST_ADMIN_PASSWORD}
      - ./ci/run-integration-tests.sh 3

---
kind: secret
name: target_username
get:
  path: liquid/ci/drone.target
  name: username

---
kind: secret
name: target_password
get:
  path: liquid/ci/drone.target
  name: password

---
kind: secret
name: target_hostname
get:
  path: liquid/ci/drone.target
  name: hostname

---
kind: secret
name: target_port
get:
  path: liquid/ci/drone.target
  name: port

---
kind: secret
name: test_admin_password
get:
  path: liquid/ci/drone.target
  name: test_admin_password
