kind: pipeline
name: test

steps:
- name: flake8
  image: python:3.7
  commands:
  - pip install flake8 > /dev/null
  - flake8

---
kind: pipeline
name: qemu

# magic undocumented feature!
# https://discourse.drone.io/t/how-to-limit-build-concurrency-per-project/3500
concurrency:
  limit: 3

depends_on:
- test

steps:
- name: deploy to qemu
  image: vmck/vagrant-vmck:0.4.1
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER"
  - vagrant/deploy-vmck

---
kind: pipeline
name: deploy to demo

concurrency:
  limit: 1

depends_on:
- qemu

steps:
- name: do it
  image: python:3.7-stretch
  privileged: true
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  - name: node
    path: /opt/node
  - name: cluster-var
    path: /opt/cluster/var
  commands:
  - cd /opt/node
  - curl https://get.docker.com/ | sh -
  - apt-get -yqq update
  - apt-get -yqq install python3-venv python3-pip git curl unzip
  - pip3 install pipenv
  - pipenv install
  - git --version
  - docker --version
  - python --version
  - ./liquid alloc drone drone
  # - liquid liquid.py halt
  # - sleep 13
  - git status -s || ( echo "GIT TREE DIRTY" && exit 1 )
  - git fetch -ap
  - git reset --hard origin/demo
  - git status
  - ./liquid deploy || ./liquid deploy

trigger:
  status:
  - success
  branch:
  - demo
  event:
  - push

volumes:
- name: docker-sock
  host:
      path: /var/run/docker.sock
- name: node
  host:
      path: /opt/node
- name: cluster-var
  host:
      path: /opt/cluster/var
