kind: pipeline
name: test

steps:
- name: flake8
  image: python:3.7
  commands:
  - pip install flake8 > /dev/null
  - flake8

---
kind: pipeline
name: qemu

# magic undocumented feature!
# https://discourse.drone.io/t/how-to-limit-build-concurrency-per-project/3500
concurrency:
  limit: 2

depends_on:
- test

steps:
- name: deploy to qemu
  image: vmck/vagrant-vmck:0.2.1
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER"
  - vagrant/deploy-vmck

---
kind: pipeline
name: deploy to demo

concurrency:
  limit: 1

depends_on:
- qemu

steps:
- name: do it
  image: docker
  privileged: true
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - while docker ps deploy-demo; do sleep 5 && echo waiting; done
  - CONTAINER=$(./ci/launch-deploy-demo-container)
  - docker logs -f $CONTAINER &
  - sleep 10

trigger:
  status:
  - success
  branch:
  - demo
  event:
  - push

volumes:
- name: docker-sock
  host:
      path: /var/run/docker.sock
