kind: pipeline
name: test

steps:
- name: flake8
  image: python:3.7
  commands:
  - pip install flake8 > /dev/null
  - flake8

---
kind: pipeline
name: qemu

# magic undocumented feature!
# https://discourse.drone.io/t/how-to-limit-build-concurrency-per-project/3500
concurrency:
  limit: 2

depends_on:
- test

steps:
- name: deploy to qemu
  image: vmck/vagrant-vmck:0.4.1
  commands:
  - export VMCK_URL=http://$VMCK_IP:$VMCK_PORT
  - export VMCK_NAME="drone $DRONE_REPO:$DRONE_BRANCH#$DRONE_BUILD_NUMBER"
  - vagrant/deploy-vmck
