#!/bin/bash -ex

apt-get -yqq update && apt-get -yqq install git curl
curl https://get.docker.com/ | sh -

git --version
docker --version

git fetch -a
git checkout master
git pull

pip install -r requirements.txt
python --version
python liquid.py alloc drone drone
sleep 5
python liquid.py halt
sleep 13
python liquid.py deploy
