#!/bin/bash -e

cd "$( dirname "${BASH_SOURCE[0]}" )"

export MACHINE_NAME="drone-$DRONE_BUILD_NUMBER"
export PATH="/sbin:$PATH"

echo "Starting Vagrant"
set -x
set +e
vagrant up --provider=vmck --no-provision
echo 'sudo shutdown +15' | vagrant ssh
vagrant provision
ret=$?

set +x
echo
echo "Stats"
vagrant ssh <<EOF
set -x
uname -a
w
df -h
free -h
EOF

echo
echo "Destroying Vagrant"
vagrant destroy -f
exit $ret
