#!/bin/bash -e

cd "$( dirname "${BASH_SOURCE[0]}" )"

echo "Vagrant"
VAGRANT_VERSION=2.2.4
(set -x
  curl -OL https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
  sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
  vagrant plugin install vagrant-digitalocean
)

echo "Decrypting private ssh key"
# travis encrypt-file id_rsa
(set -x
  openssl aes-256-cbc -K $encrypted_ec501d2f76a5_key -iv $encrypted_ec501d2f76a5_iv -in id_rsa.enc -out id_rsa -d
  chmod 600 id_rsa
  ssh-keygen -e -f id_rsa > id_rsa.pub
)

echo "Running Vagrant"
# travis encrypt DO_TOKEN="$DO_TOKEN" --add
(set -x
  vagrant up --debug
)
