# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define(ENV['DO_BUILD_NAME'] || ("liquid-vagrant-" + `hostname`.strip))

  config.vm.provider :virtualbox do |virtualbox, override|
    virtualbox.memory = 8192
    virtualbox.cpus = 2
  end

  config.vm.provider :digital_ocean do |provider, override|
    do_token = ENV['DO_TOKEN'] || abort("need DO_TOKEN in your environment")
    do_region = ENV['DO_REGION'] || "fra1"

    override.vm.box = "digital_ocean"
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    override.vm.provision :shell, path: "provision-do.sh", env: {"DO_TOKEN" => do_token}
    override.nfs.functional = false
    override.ssh.private_key_path = ENV['DO_SSH_PRIVATE_KEY_PATH'] || '~/.ssh/id_rsa'

    provider.token = do_token
    provider.region = do_region
    provider.ssh_key_name = 'vagrant'
    provider.image = 'ubuntu-18-04-x64'
    provider.size = 's-4vcpu-8gb'
  end

  config.vm.provider :libvirt do |libvirt, override|
    override.vm.box = "generic/ubuntu1804"
    libvirt.memory = 8192
    libvirt.cpus = 2
  end

  config.vm.network :forwarded_port, guest: 80, host: 1380, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 4646, host: 14646, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8500, host: 18500, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 8200, host: 18200, host_ip: "127.0.0.1"


  config.vm.synced_folder "..", "/opt/node", type: "rsync",
    rsync__exclude: [".vagrant/", ".git/", "__pycache__/",
                     "liquid.ini", "venv/", "volumes/", "collections/"]

  config.vm.provision :shell, path: "provision-cluster.sh"
  config.vm.provision :shell, path: "provision-liquid.sh"

end
