repos=(
        liquidinvestigations/hoover-snoop2
        liquidinvestigations/hoover-search
        liquidinvestigations/hoover-ui
        liquidinvestigations/core
        liquidinvestigations/hypothesis-h
        liquidinvestigations/codimd-server
        liquidinvestigations/h-client
)
