#!/bin/bash -ex
cd /opt/node

if ! [ -d collections/testdata ]; then
  git clone https://github.com/liquidinvestigations/testdata collections/testdata
fi

echo "Add some collections, check resources and deploy"
cp ci/conf/1-with-collections.ini liquid.ini

./liquid resources
./liquid deploy

echo "Process all, Do a backup"
#until ./liquid dockerexec hoover:snoop ./manage.py workisdone testdata; do sleep 15; done
sleep 60
./liquid backup ./backup
ls -aRlh ./backup

zcat backup/collection-testdata/pg.sql.gz | grep -q "PostgreSQL database dump complete"
tar tz < backup/collection-testdata/es.tgz | grep -q 'index.latest'
#tar tz < backup/collection-testdata/blobs.tgz | grep -q '6b/2b/b2ac1b581c3dc6c3c19197b0603a83f2440fb4e2b74f2fe0b76f50e240bf'
./liquid backup --no-es --no-pg --no-apps ./backup2
./liquid backup --no-blobs --no-apps --collection testdata --collection uploads ./backup3
./liquid restore-collection ./backup/collection-testdata testdata2

echo "Remove all collections, gc, restore from backup"
cp ci/conf/1-no-collections.ini liquid.ini
./liquid nomadgc
./liquid deploy --no-secrets
./liquid dockerexec hoover:snoop ./manage.py purge --force
./liquid restore-all-collections ./backup

echo "Restore apps"
./liquid restore-apps ./backup

echo "Restore apps after wipe"
docker kill cluster
docker kill $(docker ps -q)
docker ps
sudo rm -rf /opt/node/volumes/*
sudo rm -rf /opt/cluster/var/*
echo
docker start cluster
docker exec cluster ./cluster.py wait
./liquid deploy
./liquid restore-all-collections ./backup
./liquid restore-apps ./backup
