#!/bin/bash
set -ex

#cd /opt/node
cd "$(dirname ${BASH_SOURCE[0]})/../.."
BACKUP="$(dirname $PWD)/backups"

echo "Make a Backup"
cp ci/conf/1-with-collections-stopped.ini liquid.ini
./liquid deploy || ( set -ex; echo "backup test: DEPLOY 1 failed. trying again..." && ./liquid deploy )
./liquid backup $BACKUP/backup

echo "Check backup"
ls -aRlh $BACKUP/backup

zcat $BACKUP/backup/collection-testdata/pg.sql.gz | grep -q "PostgreSQL database dump complete"
tar tz < $BACKUP/backup/collection-testdata/es.tgz | grep -q 'index.latest'
# tar tz < $BACKUP/backup/collection-testdata/blobs.tgz | grep -q '6b/2b/b2ac1b581c3dc6c3c19197b0603a83f2440fb4e2b74f2fe0b76f50e240bf'
./liquid backup --no-es --no-pg --no-apps $BACKUP/backup2
./liquid backup --no-blobs --no-apps --collection testdata --collection uploads $BACKUP/backup3
./liquid restore-collection $BACKUP/backup/collection-testdata testdata2

echo "Remove all collections, gc, restore from backup"
cp ci/conf/1-no-collections.ini liquid.ini
./liquid nomadgc
./liquid deploy
./liquid dockerexec hoover:snoop ./manage.py purge --force || (
  sleep 45 && ./liquid dockerexec hoover:snoop ./manage.py purge --force
)
./liquid restore-all-collections $BACKUP/backup

echo "Restore apps"
./liquid restore-apps $BACKUP/backup

echo "Restore apps after wipe"
docker kill cluster
docker kill $(docker ps -q)
docker ps
sudo rm -rf volumes/*
sudo rm -rf /opt/cluster/var/*
echo
docker start cluster
docker exec cluster ./cluster.py wait
sudo chmod a+r /opt/cluster/var/vault-secrets.ini

./liquid deploy || ./liquid deploy
./liquid restore-all-collections $BACKUP/backup || ( sleep 45 && ./liquid restore-all-collections $BACKUP/backup )
./liquid restore-apps $BACKUP/backup || ( sleep 45 && o./liquid restore-apps $BACKUP/backup )

echo "Script: Export Dokuwiki into Wiki.js"
./scripts/export-dokuwiki-into-wikijs.sh

