#!/bin/bash
set -ex

#cd /opt/node
cd "$(dirname ${BASH_SOURCE[0]})/../.."

cp ci/conf/1-with-collections.ini liquid.ini
./liquid deploy

set -x
echo "Run UI test suite... (2nd pass)"
(cd ./ci/ui/ && ./run_ui_tests.sh) || (echo "!!!\nUI TESTS FAILED! SLEEPING 30min\n!!!!" && sleep 1800 && exit 1) || true
