#!/bin/bash -ex

#cd /opt/node
cd "$(dirname ${BASH_SOURCE[0]})/../.."

cp ci/conf/1-with-collections.ini liquid.ini
./liquid deploy

echo "Sleeping 5 minutes to allow for login before next test."
sleep 300
