#!/bin/bash -ex

apt-get -yqq update && apt-get -yqq install python3-venv python3-pip git curl unzip
pip3 install pipenv
pipenv install

curl https://get.docker.com/ | sh -

git --version
docker --version
python --version


./liquid alloc drone drone
sleep 5

#liquid liquid.py halt
#sleep 13

git fetch -a
git checkout master
git pull

./liquid deploy
